apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-extra-api-settings
spec:
  forms:
    - group: shiki
      label: Shiki 代码高亮
      formSchema:
        - $formkit: checkbox
          name: enabledShikiRender
          id: enabledShikiRender
          key: enabledShikiRender
          label: 自动渲染
          help: 启用之后会自动渲染文章和单页中的代码块。注：Finder API 渲染不受此配置项影响。
          value: true
        - $formkit: code
          label: 自定义注入 CSS 样式
          if: $get(enabledShikiRender).value
          name: inlineStyle
          key: inlineStyle
          help: 启用自动渲染时将在页面 head 注入样式以优化 Shiki 渲染效果，默认值提供了边距调整/行号显示/基于媒体查询的明暗切换功能。
          language: css
          height: 150px
          value: |
            div pre.shiki {
              border-radius: 1rem;
              padding: 1rem; !important
            }
            
            div pre.shiki code {
              counter-reset: count;
              padding: 0; !important
            }
            
            div.light pre.shiki code {
              display: block;
            }
            
            div.dark pre.shiki code {
              display: none;
            }
            
            @media (prefers-color-scheme: dark) {
              div.light pre.shiki code {
                display: none;
              }
            
              div.dark pre.shiki code {
                display: block;
              }
            }
            
            div pre.shiki code .line:before {
              content: counter(count);
              counter-increment: count;
              text-align: right;
              color: #24292e80;
              width: 1em;
              margin-right: 1.5rem;
              display: inline-block;
            }
            
            div.dark pre.shiki code .line:before {
              content: counter(count);
              counter-increment: count;
              text-align: right;
              color: #e1e4e880;
              width: 1rem;
              margin-right: 1.5rem;
              display: inline-block;
            }
        - $formkit: select
          label: 额外注入规则
          if: $get(enabledShikiRender).value
          name: extraInjectPaths
          key: extraInjectPaths
          autoSelect: false
          allowCreate: true
          clearable: true
          multiple: true
          searchable: true
          help: 默认情况下，只有文章和单页会被注入上方的内联样式。如果你希望在其他路径下的页面也注入，请在此添加对应的路径规则，支持通配符 * 。例如 /docs/** 表示 Docsme 生成的所有文档页面都会被注入。
          value:
            - /moments/**
            - /docs/**
          options:
            - label: 瞬间（/moments/**）
              value: /moments/**
            - label: Docsme 文档（/docs/**）
              value: /docs/**
        - $formkit: select
          if: "$enabledDoubleRenderMode === false"
          name: theme
          key: theme
          label: 主题
          value: github-light
          validation: required
          searchable: true
          options:
            - label: Andromeeda（dark）
              value: andromeeda
            - label: Aurora X（dark）
              value: aurora-x
            - label: Ayu Dark（dark）
              value: ayu-dark
            - label: Catppuccin Frappé（dark）
              value: catppuccin-frappe
            - label: Catppuccin Latte（light）
              value: catppuccin-latte
            - label: Catppuccin Macchiato（dark）
              value: catppuccin-macchiato
            - label: Catppuccin Mocha（dark）
              value: catppuccin-mocha
            - label: Dark Plus（dark）
              value: dark-plus
            - label: Dracula Theme（dark）
              value: dracula
            - label: Dracula Theme Soft（dark）
              value: dracula-soft
            - label: Everforest Dark（dark）
              value: everforest-dark
            - label: Everforest Light（light）
              value: everforest-light
            - label: GitHub Dark（dark）
              value: github-dark
            - label: GitHub Dark Default（dark）
              value: github-dark-default
            - label: GitHub Dark Dimmed（dark）
              value: github-dark-dimmed
            - label: GitHub Dark High Contrast（dark）
              value: github-dark-high-contrast
            - label: GitHub Light（light）
              value: github-light
            - label: GitHub Light Default（light）
              value: github-light-default
            - label: GitHub Light High Contrast（light）
              value: github-light-high-contrast
            - label: Gruvbox Dark Hard（dark）
              value: gruvbox-dark-hard
            - label: Gruvbox Dark Medium（dark）
              value: gruvbox-dark-medium
            - label: Gruvbox Dark Soft（dark）
              value: gruvbox-dark-soft
            - label: Gruvbox Light Hard（light）
              value: gruvbox-light-hard
            - label: Gruvbox Light Medium（light）
              value: gruvbox-light-medium
            - label: Gruvbox Light Soft（light）
              value: gruvbox-light-soft
            - label: Houston（dark）
              value: houston
            - label: Kanagawa Dragon（dark）
              value: kanagawa-dragon
            - label: Kanagawa Lotus（light）
              value: kanagawa-lotus
            - label: Kanagawa Wave（dark）
              value: kanagawa-wave
            - label: LaserWave（dark）
              value: laserwave
            - label: Light Plus（light）
              value: light-plus
            - label: Material Theme（dark）
              value: material-theme
            - label: Material Theme Darker（dark）
              value: material-theme-darker
            - label: Material Theme Lighter（light）
              value: material-theme-lighter
            - label: Material Theme Ocean（dark）
              value: material-theme-ocean
            - label: Material Theme Palenight（dark）
              value: material-theme-palenight
            - label: Min Dark（dark）
              value: min-dark
            - label: Min Light（light）
              value: min-light
            - label: Monokai（dark）
              value: monokai
            - label: Night Owl（dark）
              value: night-owl
            - label: Nord（dark）
              value: nord
            - label: One Dark Pro（dark）
              value: one-dark-pro
            - label: One Light（light）
              value: one-light
            - label: Plastic（dark）
              value: plastic
            - label: Poimandres（dark）
              value: poimandres
            - label: Red（dark）
              value: red
            - label: Rosé Pine（dark）
              value: rose-pine
            - label: Rosé Pine Dawn（light）
              value: rose-pine-dawn
            - label: Rosé Pine Moon（dark）
              value: rose-pine-moon
            - label: Slack Dark（dark）
              value: slack-dark
            - label: Slack Ochin（light）
              value: slack-ochin
            - label: Snazzy Light（light）
              value: snazzy-light
            - label: Solarized Dark（dark）
              value: solarized-dark
            - label: Solarized Light（light）
              value: solarized-light
            - label: Synthwave '84（dark）
              value: synthwave-84
            - label: Tokyo Night（dark）
              value: tokyo-night
            - label: Vesper（dark）
              value: vesper
            - label: Vitesse Black（dark）
              value: vitesse-black
            - label: Vitesse Dark（dark）
              value: vitesse-dark
            - label: Vitesse Light（light）
              value: vitesse-light
        - $formkit: checkbox
          label: 明暗双倍渲染模式
          name: enabledDoubleRenderMode
          key: enabledDoubleRenderMode
          value: true
        - $formkit: text
          if: "$enabledDoubleRenderMode === true"
          name: lightCodeClass
          key: lightCodeClass
          label: 亮色主题代码块类名
          value: light
          help: 文章内容中代码块渲染后的类名，默认为 light。
        - $formkit: text
          if: "$enabledDoubleRenderMode === true"
          name: darkCodeClass
          key: darkCodeClass
          label: 暗色主题代码块类名
          value: dark
          help: 文章内容中代码块渲染后的类名，默认为 dark。
        - $formkit: select
          if: "$enabledDoubleRenderMode === true"
          name: lightTheme
          key: lightTheme
          label: 亮色主题
          value: github-light
          validation: required
          searchable: true
          options:
            - label: Andromeeda（dark）
              value: andromeeda
            - label: Aurora X（dark）
              value: aurora-x
            - label: Ayu Dark（dark）
              value: ayu-dark
            - label: Catppuccin Frappé（dark）
              value: catppuccin-frappe
            - label: Catppuccin Latte（light）
              value: catppuccin-latte
            - label: Catppuccin Macchiato（dark）
              value: catppuccin-macchiato
            - label: Catppuccin Mocha（dark）
              value: catppuccin-mocha
            - label: Dark Plus（dark）
              value: dark-plus
            - label: Dracula Theme（dark）
              value: dracula
            - label: Dracula Theme Soft（dark）
              value: dracula-soft
            - label: Everforest Dark（dark）
              value: everforest-dark
            - label: Everforest Light（light）
              value: everforest-light
            - label: GitHub Dark（dark）
              value: github-dark
            - label: GitHub Dark Default（dark）
              value: github-dark-default
            - label: GitHub Dark Dimmed（dark）
              value: github-dark-dimmed
            - label: GitHub Dark High Contrast（dark）
              value: github-dark-high-contrast
            - label: GitHub Light（light）
              value: github-light
            - label: GitHub Light Default（light）
              value: github-light-default
            - label: GitHub Light High Contrast（light）
              value: github-light-high-contrast
            - label: Gruvbox Dark Hard（dark）
              value: gruvbox-dark-hard
            - label: Gruvbox Dark Medium（dark）
              value: gruvbox-dark-medium
            - label: Gruvbox Dark Soft（dark）
              value: gruvbox-dark-soft
            - label: Gruvbox Light Hard（light）
              value: gruvbox-light-hard
            - label: Gruvbox Light Medium（light）
              value: gruvbox-light-medium
            - label: Gruvbox Light Soft（light）
              value: gruvbox-light-soft
            - label: Houston（dark）
              value: houston
            - label: Kanagawa Dragon（dark）
              value: kanagawa-dragon
            - label: Kanagawa Lotus（light）
              value: kanagawa-lotus
            - label: Kanagawa Wave（dark）
              value: kanagawa-wave
            - label: LaserWave（dark）
              value: laserwave
            - label: Light Plus（light）
              value: light-plus
            - label: Material Theme（dark）
              value: material-theme
            - label: Material Theme Darker（dark）
              value: material-theme-darker
            - label: Material Theme Lighter（light）
              value: material-theme-lighter
            - label: Material Theme Ocean（dark）
              value: material-theme-ocean
            - label: Material Theme Palenight（dark）
              value: material-theme-palenight
            - label: Min Dark（dark）
              value: min-dark
            - label: Min Light（light）
              value: min-light
            - label: Monokai（dark）
              value: monokai
            - label: Night Owl（dark）
              value: night-owl
            - label: Nord（dark）
              value: nord
            - label: One Dark Pro（dark）
              value: one-dark-pro
            - label: One Light（light）
              value: one-light
            - label: Plastic（dark）
              value: plastic
            - label: Poimandres（dark）
              value: poimandres
            - label: Red（dark）
              value: red
            - label: Rosé Pine（dark）
              value: rose-pine
            - label: Rosé Pine Dawn（light）
              value: rose-pine-dawn
            - label: Rosé Pine Moon（dark）
              value: rose-pine-moon
            - label: Slack Dark（dark）
              value: slack-dark
            - label: Slack Ochin（light）
              value: slack-ochin
            - label: Snazzy Light（light）
              value: snazzy-light
            - label: Solarized Dark（dark）
              value: solarized-dark
            - label: Solarized Light（light）
              value: solarized-light
            - label: Synthwave '84（dark）
              value: synthwave-84
            - label: Tokyo Night（dark）
              value: tokyo-night
            - label: Vesper（dark）
              value: vesper
            - label: Vitesse Black（dark）
              value: vitesse-black
            - label: Vitesse Dark（dark）
              value: vitesse-dark
            - label: Vitesse Light（light）
              value: vitesse-light
        - $formkit: select
          if: "$enabledDoubleRenderMode === true"
          name: darkTheme
          key: darkTheme
          label: 暗色主题
          value: github-dark
          validation: required
          searchable: true
          options:
            - label: Andromeeda（dark）
              value: andromeeda
            - label: Aurora X（dark）
              value: aurora-x
            - label: Ayu Dark（dark）
              value: ayu-dark
            - label: Catppuccin Frappé（dark）
              value: catppuccin-frappe
            - label: Catppuccin Latte（light）
              value: catppuccin-latte
            - label: Catppuccin Macchiato（dark）
              value: catppuccin-macchiato
            - label: Catppuccin Mocha（dark）
              value: catppuccin-mocha
            - label: Dark Plus（dark）
              value: dark-plus
            - label: Dracula Theme（dark）
              value: dracula
            - label: Dracula Theme Soft（dark）
              value: dracula-soft
            - label: Everforest Dark（dark）
              value: everforest-dark
            - label: Everforest Light（light）
              value: everforest-light
            - label: GitHub Dark（dark）
              value: github-dark
            - label: GitHub Dark Default（dark）
              value: github-dark-default
            - label: GitHub Dark Dimmed（dark）
              value: github-dark-dimmed
            - label: GitHub Dark High Contrast（dark）
              value: github-dark-high-contrast
            - label: GitHub Light（light）
              value: github-light
            - label: GitHub Light Default（light）
              value: github-light-default
            - label: GitHub Light High Contrast（light）
              value: github-light-high-contrast
            - label: Gruvbox Dark Hard（dark）
              value: gruvbox-dark-hard
            - label: Gruvbox Dark Medium（dark）
              value: gruvbox-dark-medium
            - label: Gruvbox Dark Soft（dark）
              value: gruvbox-dark-soft
            - label: Gruvbox Light Hard（light）
              value: gruvbox-light-hard
            - label: Gruvbox Light Medium（light）
              value: gruvbox-light-medium
            - label: Gruvbox Light Soft（light）
              value: gruvbox-light-soft
            - label: Houston（dark）
              value: houston
            - label: Kanagawa Dragon（dark）
              value: kanagawa-dragon
            - label: Kanagawa Lotus（light）
              value: kanagawa-lotus
            - label: Kanagawa Wave（dark）
              value: kanagawa-wave
            - label: LaserWave（dark）
              value: laserwave
            - label: Light Plus（light）
              value: light-plus
            - label: Material Theme（dark）
              value: material-theme
            - label: Material Theme Darker（dark）
              value: material-theme-darker
            - label: Material Theme Lighter（light）
              value: material-theme-lighter
            - label: Material Theme Ocean（dark）
              value: material-theme-ocean
            - label: Material Theme Palenight（dark）
              value: material-theme-palenight
            - label: Min Dark（dark）
              value: min-dark
            - label: Min Light（light）
              value: min-light
            - label: Monokai（dark）
              value: monokai
            - label: Night Owl（dark）
              value: night-owl
            - label: Nord（dark）
              value: nord
            - label: One Dark Pro（dark）
              value: one-dark-pro
            - label: One Light（light）
              value: one-light
            - label: Plastic（dark）
              value: plastic
            - label: Poimandres（dark）
              value: poimandres
            - label: Red（dark）
              value: red
            - label: Rosé Pine（dark）
              value: rose-pine
            - label: Rosé Pine Dawn（light）
              value: rose-pine-dawn
            - label: Rosé Pine Moon（dark）
              value: rose-pine-moon
            - label: Slack Dark（dark）
              value: slack-dark
            - label: Slack Ochin（light）
              value: slack-ochin
            - label: Snazzy Light（light）
              value: snazzy-light
            - label: Solarized Dark（dark）
              value: solarized-dark
            - label: Solarized Light（light）
              value: solarized-light
            - label: Synthwave '84（dark）
              value: synthwave-84
            - label: Tokyo Night（dark）
              value: tokyo-night
            - label: Vesper（dark）
              value: vesper
            - label: Vitesse Black（dark）
              value: vitesse-black
            - label: Vitesse Dark（dark）
              value: vitesse-dark
            - label: Vitesse Light（light）
              value: vitesse-light
