name: Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 21
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: 'ui/pnpm-lock.yaml'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: gradlew test
        run: |
          ./gradlew test
      # - name: Front test
      #   run: |
      #     cd ui
      #     pnpm test