name: Publish Node.js Runtime API

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish nodejs-runtime-api
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'nodejs-runtime-api@')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # https://github.com/actions/checkout/tree/v6.0.3
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name || github.ref }}

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # https://github.com/actions/setup-java/tree/v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # https://github.com/gradle/actions/tree/v6
        with:
          cache-read-only: false

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Publish API module
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :nodejs-runtime-api:publish --console=plain
